main_app/urls.py
from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

#Added for file uploads
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main_app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('editprofile/', views.EditProfileView.as_view(), name='editprofile'),
    path('submitEditedProfile/', views.submitEditedProfile, name='submitEditedProfile'),
    path('addClasses/', views.AddClassesView.as_view(), name='addclasses'),
    path('course/<int:pk>/', views.ClassDetailView.as_view(), name='classdetail'),
    path('filterclasses/', views.filterClasses, name='filterclasses'),
    path('addCourse/<int:pk>/', views.addCourse, name="addCourse"),
    path('removeCourse/<int:pk>/', views.removeCourse, name="removeCourse"),
    path('listClasses/', views.ListClassesView.as_view(), name='listclasses'),
    path('assignments/', views.AssignmentsView.as_view(), name='assignments'),
    path('removeAssignment/<int:pk>/', views.removeAssignment, name="removeAssignment"),
    path('addAssignment/', views.addAssignment, name="addAssignment"),
    path('accounts/', include('allauth.urls')),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('studentSearch', views.studentSearchView, name="studentSearch"),
    path('documents/', views.document_list, name='documents'),
    path('documents/upload', views.document_upload, name='document_upload'),
    path('documents/<int:pk>', views.document_delete, name='document_delete')
]

project_a_08/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

#Added for file uploads
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html")),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin
from django.contrib.auth.models import User
# Create your models here.

class Class(models.Model):
    id = models.IntegerField(default=0, primary_key=True)
    subject = models.CharField(max_length=30, default="None")
    code = models.CharField(max_length=30, default="None")
    section = models.CharField(max_length=30, default="None")
    name = models.CharField(max_length=30, default="None")
    professor = models.CharField(max_length=30, default="None")
    size = models.IntegerField(default=0)
    day = models.CharField(max_length=30, default="None")
    start_time = models.TimeField(default="00:00:00")
    end_time = models.TimeField(default="00:00:00")
    semester = models.CharField(max_length=30, default="None")
    def __str__(self):
        return f"{self.subject} {self.code}, section {self.section}"

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30, default='NULL')
    computing_id = models.CharField(max_length=30, default='NULL')
    year = models.IntegerField(default=0)
    classes = models.ManyToManyField('Class', related_name='profiles')
    def __str__(self):
        return f'{self.user} Profile'

class Assignment(models.Model):
    id = models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')
    profile = models.ForeignKey(Profile, related_name='assignments', on_delete=models.CASCADE)
    name = models.CharField(max_length=30, default='')
    description = models.CharField(max_length=200, default='')
    points = models.IntegerField(default=0)
    class_name = models.CharField(max_length=30, default='')
    release_date = models.CharField(max_length=30, default='')
    due_date = models.CharField(max_length=30, default='')
    def __str__(self):
        return f'{self.name}'

class Document(models.Model):
    title = models.CharField(max_length=50)
    document = models.FileField(upload_to='documents/')
    profile = models.ForeignKey(Profile, related_name='document_profile', on_delete=models.CASCADE, null=True)
    document_class = models.ForeignKey(Class, related_name='document_class', on_delete=models.CASCADE, null=True)
    #make new model to deal with dropdown menu and pass values to document_class
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f'{self.title}'
    

main_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile, Document, Class

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['computing_id', 'year']

class DocumentForm(forms.ModelForm):
    #document_classes = forms.ModelChoiceField(queryset=Profile.objects.all())

    class Meta:
        model = Document
        fields = ('title', 'document', 'document_class', )
        exclude = ('profile', )
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(DocumentForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['document_class'].queryset = user.profile.classes.all()
            

main_app/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.template import loader
from django.http import HttpResponse

from .models import Class, Profile, Assignment, Document
from .forms import UserUpdateForm, ProfileUpdateForm, DocumentForm

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated')
            return redirect('editprofile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'main_app/editprofile.html')

class IndexView(generic.ListView):
    model = Profile
    template_name = 'main_app/index.html'
    context_object_name = 'index'

class EditProfileView(generic.ListView):
    model = Profile
    template_name = 'main_app/editprofile.html'
    context_object_name = 'profile'

class AddClassesView(generic.ListView):
    model = Class
    template_name = 'main_app/addclasses.html'
    context_object_name = 'all_classes'
    courses = []

class ListClassesView(generic.ListView):
    model = Profile
    template_name = 'main_app/listclasses.html'
    context_object_name = 'my_classes'
    def get_queryset(self):
        return Class.objects.order_by('id')
    def get_context_data(self, **kwargs):
        context = super(ListClassesView, self).get_context_data(**kwargs)
        context['Mon'] = self.request.user.profile.classes.filter(day__icontains="M").order_by('start_time')
        context['Tue'] = self.request.user.profile.classes.filter(day__icontains="T").order_by('start_time')
        context['Wed'] = self.request.user.profile.classes.filter(day__icontains="W").order_by('start_time')
        context['Thu'] = self.request.user.profile.classes.filter(day__icontains="R").order_by('start_time')
        context['Fri'] = self.request.user.profile.classes.filter(day__icontains="F").order_by('start_time')
        return context

class ClassDetailView(generic.DetailView):
    model = Class
    template_name = 'main_app/classdetail.html'
    context_object_name = 'class_detail'
    def get_context_data(self, **kwargs):
        context = super(ClassDetailView, self).get_context_data(**kwargs)
        context['classdocs'] = Document.objects.filter(document_class=self.kwargs['pk'])
        return context

class AssignmentsView(generic.ListView):
    template_name = 'main_app/assignments.html'
    context_object_name = 'my_assignments'
    def get_queryset(self):
        return self.request.user.profile.assignments.all()

def removeAssignment(request, pk):
    if request.method == 'POST':
        assignment = Assignment.objects.get(id=pk)
        assignment.delete()
    return HttpResponseRedirect('/assignments')

def addAssignment(request):
    template_name = 'main_app/filterclasses.html'
    if request.method == 'POST':
        if request.POST.get('assignment_name') and request.POST.get('class_name') and request.POST.get('description') and request.POST.get('due_date'):
            class_name = request.POST.get('class_name')
            name = request.POST.get('assignment_name')
            due_date = request.POST.get('due_date')
            description = request.POST.get('description')
            if len(class_name) > 30:
                messages.error(request, "Error: Class name must be less than or equal to 30 characters")
                return HttpResponseRedirect('/assignments')
            if len(name) > 30:
                messages.error(request, "Error: Assignment name must be less than or equal to 30 characters")
                return HttpResponseRedirect('/assignments')
            if len(due_date) > 30:
                messages.error(request, "Error: Due date must be less than or equal to 30 characters")
                return HttpResponseRedirect('/assignments')
            if len(description) > 200:
                messages.error(request, "Error: Description must be less than or equal to 200 characters")
                return HttpResponseRedirect('/assignments')
            new_assignment = Assignment()
            new_assignment.class_name = class_name
            new_assignment.name = name
            new_assignment.due_date = due_date
            new_assignment.description = description
            new_assignment.profile = request.user.profile
            new_assignment.save()
        else:
            messages.error(request, "Blank Submission! You must submit all fields.")
    return HttpResponseRedirect('/assignments')

def submitEditedProfile(request):
    if request.method == 'POST':
        if request.POST.get('studentName') or request.POST.get('studentComputingID') or request.POST.get('studentYear'):
            name = request.POST.get('studentName')
            computing_id = request.POST.get('studentComputingID')
            year = request.POST.get('studentYear')
            if len(name) > 30:
                messages.error(request, "Error: name must be less than or equal to 30 characters")
                return HttpResponseRedirect('/')
            if len(computing_id) > 30:
                messages.error(request, "Error: computing id must be less than or equal to 30 characters")
                return HttpResponseRedirect('/')
            if (not year.isdigit() or len(year) != 4) and year:
                messages.error(request, "Error: graduation year must be a 4 digit number")
                return HttpResponseRedirect('/')
            if name: request.user.profile.name = name
            if computing_id: request.user.profile.computing_id = computing_id
            if year: request.user.profile.year = year
            request.user.profile.save()
            messages.success(request, "Successfully Submitted!")
        else:
            messages.error(request, "Blank Submission!")
    return HttpResponseRedirect('/')

def filterClasses(request):
    template_name = 'main_app/filterclasses.html'
    courses = Class.objects
    if request.method == 'POST':
        searched = request.POST.get('query')
        searchType = request.POST.get('queryType')
        if searched == '': 
            messages.error(request, "Blank query!")
            return HttpResponseRedirect('/addClasses')
        if searchType =='':
            messages.error(request, "Blank filter!")
            return HttpResponseRedirect('/addClasses')
        elif searchType == 'name': courses = Class.objects.filter(name__icontains=searched)
        elif searchType == 'code':
            vals = searched.split(' ') # vals = [course subject, course code]
            # if len is not 2, course code is invalid
            if len(vals) != 2:
                messages.error(request, "Invalid course code!")
                return HttpResponseRedirect('/addClasses')
            # filter twice
            print("subject", vals[0], "\n")
            print("code", vals[1], "\n")
            courses = Class.objects.filter(subject__icontains=vals[0])
            courses = courses.filter(code__icontains=vals[1])
        elif searchType == 'professor': courses = Class.objects.filter(professor__icontains=searched)
        elif searchType == 'subject': courses = Class.objects.filter(subject__icontains=searched)
    return render(request, template_name, {'courses':courses, 'filter':searchType})

def addCourse(request, pk):
    if request.method == 'POST':
        course = Class.objects.get(id=pk)
        request.user.profile.classes.add(course)
        request.user.profile.save()
        messages.success(request, f"{course.subject} {course.code} added!")
    return HttpResponseRedirect(f'/course/{pk}/')

def removeCourse(request, pk):
    if request.method == 'POST':
        course = Class.objects.get(id=pk)
        request.user.profile.classes.remove(course)
        request.user.profile.save()
        messages.success(request, f"{course.subject} {course.code} removed!")
    return HttpResponseRedirect(f'/course/{pk}/')

def logout_view(request):
    logout(request)
    return render(request, 'main_app/index.html')

def studentSearchView(request):
    template = loader.get_template('main_app/studentSearch.html')

    otherStudents = []

    userProfile = request.user.profile
    #userProfile = Profile.objects.all()[0]

    for c in userProfile.classes.all():
        classData = {
            'students': [],
            'class': c
        }

        for student in c.profiles.all():
            if student != userProfile:
                classData['students'].append(student)

        otherStudents.append(classData)
    context = {
        'classes': otherStudents
    }
    
    return HttpResponse(template.render(context, request))
    

# Document uploads
# https://docs.djangoproject.com/en/3.2/topics/http/file-uploads/
# https://simpleisbetterthancomplex.com/tutorial/2016/08/01/how-to-upload-files-with-django.html
# https://www.youtube.com/watch?v=nzLMA9WZqMM

def document_list(request):
    userdocs = Document.objects.filter(profile=request.user.profile)
    return render(request, 'main_app/documents.html', {'documents': userdocs})

def document_upload(request):
    user = {'user': request.user}
    form = DocumentForm(**user)
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES, **user)
        if form.is_valid():
            doc = form.save(commit=False)

main_app/templates/main_app/assignments.html
{% extends "base.html" %}

{% load static %}
{% load bootstrap5 %}


{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block content %}
<style>
p {
    word-wrap:break-word;
}
h5 {
  display: inline-block;
  margin: 0;
}
.btn-primary {
    color: #fff;
    background-color: #466197;
    border-color: #f69350;
}
.btn-primary:hover {
    background-color: #5374b6;
}
</style>
<body style= "background-color: #ebecf1;">
    <center><h1 class=" mt-5" style= "font-family:'Nunito Sans', Arial"><b>Assignments</b></h1></center>
    <br>
         <div class= "container">

             <div class="row justify-content-center">
                 <!--Assignments List (left)-->
                 <div class="col">
                    <form method="POST" action="{% url 'main_app:addAssignment' %}" style="display: inline;">
                        {% csrf_token %}
                        <input type="text" placeholder="Enter class name" name="class_name">
                        <input type="text" placeholder="Enter assignment name" name="assignment_name">
                        <input type="text" placeholder="Enter due date" name="due_date">
                        <br><br>
                        <textarea placeholder="Enter assignment description (200 character limit)" name="description" rows="4" cols="75" maxlength="200"></textarea>
                        <br>
                        <button type="submit" value="Submit" class="btn btn-primary mt-3 text-center">Add Assignment</button>
                    </form>
                 </div>
                 <!--Add Assignment (right)-->
                 <div class="col-6 text-wrap">
                    <ul class= "no-bullets text-wrap">
                        {% for assignment in my_assignments %}
                        <li>
                        <form method="POST" action="{% url 'main_app:removeAssignment' assignment.id %}"
                             style="display: inline;">
                             {% csrf_token %}
                             <button class="btn btn-danger btn-sm">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16">
                                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                  </svg>
                                </button>
                             <h5>   {{assignment.class_name}}: {{assignment.name}} - Due: {{assignment.due_date}}</h5>
                             <p>   {{assignment.description}}</p>
                         </form>
                         </li>
                         {% endfor %}
                     </ul>
                 </div>  
             </div>
         </div>
 </body>
<br><br><br><br><br>
{% endblock %}

main_app/templates/main_app/classTest.html
{% load static %}
{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% for name, data in displayData %}
    <p>{{ name }}</p>
    <select>
        {% for d in data %}
            <option value="">{{ d }}</option>
        {% endfor %}
    </select>
{% endfor %}

main_app/templates/main_app/classdetail.html
{% extends "base.html" %}

{% load static %}
{% load bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block content %}
<head>
    <title>Classes</title>
</head>

<body>
    <center><h1 class=" mt-5" style= "font-family:'Nunito Sans', Arial"><b>Class Info</b></h1><br>
    <form method="POST" action="{% url 'main_app:addCourse' class_detail.id %}" style="display: inline;">
        {% csrf_token %}
        <button class="btn btn-primary btn-sm">Add Course</button>
    </form>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <form method="POST" action="{% url 'main_app:removeCourse' class_detail.id %}" style="display: inline;">
        {% csrf_token %}
        <button class="btn btn-danger btn-sm">Remove Course</button>
    </form></center>
    <div class=" container">
        <br>
        <center><div class="card" style="width: 40rem;">
            <div class="card-header bg-light" style="font-family: 'Nunito Sans'; font-size: 32px;"><b>{{class_detail.subject}}{{class_detail.code}}</b></div>
                <div class="card-body">
                    <h3 class="card-title">{{class_detail.name}}</h3>
                    <br>
                    <h4 class="card-subtitle mb-2 text-muted">Course Information:</h4>
                    <p class="card-text">
                        <p>Professor: {{class_detail.professor}}</p>
                        <p>Meeting days:
                        {% if "M" in class_detail.day %}
                        Mo
                        {% endif %}
                        {% if "T" in class_detail.day %}
                        Tu
                        {% endif %}
                        {% if "W" in class_detail.day %}
                        We
                        {% endif %}
                        {% if "R" in class_detail.day %}
                        Th
                        {% endif %}
                        {% if "F" in class_detail.day %}
                        Fr
                        {% endif %} </p>
                        <p>Start time: {{class_detail.start_time}}</p>
                        <p>End time: {{class_detail.end_time}}</p>
                        <p>Section: {{class_detail.section}}</p>
                        <p>Size: {{class_detail.size}}</p>
                        <br>
                        <a href="/addClasses">Return to Class Selection</a>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/">Return to Profile</a>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/listClasses">Return to Schedule</a>
                    </p>
                </div>
        </div></center>
        <br><br>        
        <div class="list-group">
            <center><div class="card-header bg-light w-75" style="font-family: 'Nunito Sans'; font-size: 28px;"><b>{{class_detail.subject}}{{class_detail.code}} Documents</b></div></center>
            {% if classdocs %}
                {% for document in classdocs %}
                    <center><div class="list-group-item w-75">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1"><a target="_blank">{{ document.title }}</a></h5>
                            <br>
                            <small class="text-muted">{{document.date}} (UTC)</small>
                        </div>
                        <div class="d-flex w-100 justify-content-between">
                            <p class="d-inline mb-1">Uploaded by: {{document.profile.user}}</p>
                            <center><a href="{{ document.document.url }}" class="btn btn-primary btn-sm" target="blank" download>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-up-right" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M8.636 3.5a.5.5 0 0 0-.5-.5H1.5A1.5 1.5 0 0 0 0 4.5v10A1.5 1.5 0 0 0 1.5 16h10a1.5 1.5 0 0 0 1.5-1.5V7.864a.5.5 0 0 0-1 0V14.5a.5.5 0 0 1-.5.5h-10a.5.5 0 0 1-.5-.5v-10a.5.5 0 0 1 .5-.5h6.636a.5.5 0 0 0 .5-.5z"/>
                                    <path fill-rule="evenodd" d="M16 .5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h3.793L6.146 9.146a.5.5 0 1 0 .708.708L15 1.707V5.5a.5.5 0 0 0 1 0v-5z"/>
                                </svg>
                                &nbsp;View Document</a>
                        </div>
                    </div></center>
                {% endfor %}
            {% else %}
            <center><div class="list-group-item w-75">
                <p class="d-inline mb-1">This class currently has no documents.</p>
            </div></center>
            {% endif %}
        </div>
    </div><br><br><br><br><br>
</body>

<style type="text/css">
    body{
      color: #1a202c;
      text-align: left;
      background-color: #ebecf1;    
    }
    
    .card {
        background-color: #fff;
    }
    
    .btn-primary {
        color: #fff;
        background-color: #466197;
        border-color: #f69350;
    }
    .btn-primary:hover {
        background-color: #5374b6;
    }
    </style>
{% endblock %}

main_app/templates/main_app/documents.html
{% extends "base.html" %}

{% load static %}
{% load bootstrap5 %}


{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block content %}
<head>
    <title>Documents</title>
    <link rel="stylesheet" type="text/css" href="{% static 'main_app/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
  <center><h1 class=" mt-5" style= "font-family:'Nunito Sans', Arial"><b>My Documents</b></h1><br>
  <!-- Upload button -->
  <a href="{% url 'main_app:document_upload'%}" class="btn btn-primary" >
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-upload" viewBox="0 0 16 18">
      <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
      <path d="M7.646 1.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 2.707V11.5a.5.5 0 0 1-1 0V2.707L5.354 4.854a.5.5 0 1 1-.708-.708l3-3z"/>
    </svg>
    &nbsp;Upload A Document</a></center>
  <br><br>

<!-- Display documents -->
{% if documents %}
<div class = "container">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for document in documents %}
    <div class="col">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title d-flex justify-content-center">{{ document.title }}</h5>
          <p class="card-text d-flex justify-content-center">Date Uploaded: {{ document.date }} (UTC)<br>Class: {{ document.document_class }} </p><br>
          <form method="post" action="{% url 'main_app:document_delete' document.pk %}">
            <center><a href="{{ document.document.url }}" class="btn btn-primary btn-sm" target="blank" download>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-up-right" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8.636 3.5a.5.5 0 0 0-.5-.5H1.5A1.5 1.5 0 0 0 0 4.5v10A1.5 1.5 0 0 0 1.5 16h10a1.5 1.5 0 0 0 1.5-1.5V7.864a.5.5 0 0 0-1 0V14.5a.5.5 0 0 1-.5.5h-10a.5.5 0 0 1-.5-.5v-10a.5.5 0 0 1 .5-.5h6.636a.5.5 0 0 0 .5-.5z"/>
                <path fill-rule="evenodd" d="M16 .5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h3.793L6.146 9.146a.5.5 0 1 0 .708.708L15 1.707V5.5a.5.5 0 0 0 1 0v-5z"/>
              </svg>
              &nbsp;View Document</a>
            {% csrf_token %}
            &nbsp;&nbsp;<button type="submit" class="btn btn-danger btn-sm">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
              </svg>
              &nbsp;Delete</button>
          </form></center>
        </div>
      </div>
    </div>
  {% endfor %}
  </div>
</div>

<!-- No documents message -->
{% else %}
  <br>
  <center><p style = "font-size: 19px">You currently have no documents.</p></center>
{% endif %} 
  <br>
  <br>
  <br>
  <br>
</body>

<style type="text/css">
body{
  color: #1a202c;
  text-align: left;
  background-color: #ebecf1;    
}

.card {
    background-color: #fff;
}

.btn-primary {
    color: #fff;
    background-color: #466197;
    border-color: #f69350;
}
.btn-primary:hover {
    background-color: #5374b6;
}
</style>
{% endblock %}