main_app/urls.py
from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

#Added for file uploads
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main_app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('editprofile/', views.EditProfileView.as_view(), name='editprofile'),
    path('submitEditedProfile/', views.submitEditedProfile, name='submitEditedProfile'),
    path('addClasses/', views.AddClassesView.as_view(), name='addclasses'),
    path('course/<int:pk>/', views.ClassDetailView.as_view(), name='classdetail'),
    path('filterclasses/', views.filterClasses, name='filterclasses'),
    path('addCourse/<int:pk>/', views.addCourse, name="addCourse"),
    path('removeCourse/<int:pk>/', views.removeCourse, name="removeCourse"),
    path('listClasses/', views.ListClassesView.as_view(), name='listclasses'),
    path('assignments/', views.AssignmentsView.as_view(), name='assignments'),
    path('removeAssignment/<int:pk>/', views.removeAssignment, name="removeAssignment"),
    path('addAssignment/', views.addAssignment, name="addAssignment"),
    path('accounts/', include('allauth.urls')),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('studentSearch', views.studentSearchView, name="studentSearch"),
    path('documents/', views.document_list, name='documents'),
    path('documents/upload', views.document_upload, name='document_upload'),
    path('documents/<int:pk>', views.document_delete, name='document_delete')
]

project_a_08/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

#Added for file uploads
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html")),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% load socialaccount %}

<!-- Navbar CSS -->
<style type="text/css">
  .container p-5 my-5 text-black rounded border border-warning {
    color: rgb(37, 22, 119);
  }
  .btn-primary {
      color: #fff;
      background-color: #466197;
      border-color: #f69350;
  }
  .btn-primary:hover {
      background-color: #5374b6;
  }
  * {box-sizing: border-box}
  @media screen and (max-width: 500px) {
    .navbar a {
      float: none;
      display: block;
      width: 100%;
      text-align: left;
    }
  }
  .navbar {
    width: 100%;
    height: 68px;
    background-color: rgb(75, 166, 218);
    overflow: hidden;
  }
  
  .navbar a {
    float: left;
    padding: 12px;
    color: rgb(255, 255, 255);
    text-decoration: none;
    font-size: 16px;
    width: 100%; /* 5 links of equal widths */
    text-align: center;
  }
  
  .navbar a:hover {
    background-color: #eb9422; /*rgb(69, 180, 245)*/
    background-image: var(--bs-gradient);
    color: #080e14;
  }
  
  .navbar a.active {
    background-color: #eb9422;
    background-image: var(--bs-gradient);
  }
  .navbar a.logo {
    background-color: rgb(75, 166, 218);
    background-image: none;
    color:rgb(255, 255, 255)
  }
  
  ul.no-bullets {
    list-style-type: none; /* Remove bullets */
    padding: 0; /* Remove padding */
    margin: 0; /* Remove margins */
  }

  </style>

<head>
  <title>Wahoo Notes</title>
  <!-- CSS only -->
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="{% static 'main_app/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
  <!-- Bootstrap icons -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">
  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@700&family=Roboto:wght@300&display=swap"
    rel="stylesheet">
  <!-- JQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<!DOCTYPE html>
<html lang = "en">
    <body>
      <nav class="navbar navbar-expand-lg shadow" style="background-color: #232D4B">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto no-bullets">
            <li>
              <a class= "navbar-brand logo " href="{% url 'main_app:index'%}" style="font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif; font-size: 28px; color:rgb(236, 132, 47); background-color: #232D4B">
                Wahoo
                <p style = "position:relative; right:3px; bottom:1px; font-family:'Lucida Handwriting', Impact, Arial, Serif; display:inline; font-size:26px; color:white; text-shadow:1px 1px #a9afc7">Notes</p>
              </a>
            </li>
          </ul>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent" style= "font-family:'Roboto', Arial">
            <ul class="navbar-nav ms-auto" style="font-family:'Roboto', Arial; font-weight:bold">
              <li class="nav-item">
                <a {% if request.resolver_match.url_name == '' %}class="nav-link active rounded"{% else %}class="nav-link rounded"{% endif %} href="{% url 'main_app:index'%}">Home</a>
              </li>
              <li class="nav-item">
                <a {% if request.resolver_match.url_name == 'addclasses' %}class="nav-link active rounded"{% else %}class="nav-link rounded"{% endif %} href="{% url 'main_app:addclasses'%}">Class Search</a>
              </li>
              <li class="nav-item">
                <a {% if request.resolver_match.url_name == 'listclasses' %}class="nav-link active rounded"{% else %}class="nav-link rounded"{% endif %} href="{% url 'main_app:listclasses'%}">View Schedule</a>
              </li>
              <li class="nav-item">
                <a {% if request.resolver_match.url_name == 'assignments' %}class="nav-link active rounded"{% else %}class="nav-link rounded"{% endif %} href="{% url 'main_app:assignments'%}">Assignments</a>
              </li>
              <li class="nav-item">
                <a {% if request.resolver_match.url_name == 'documents' %}class="nav-link active rounded"{% else %}class="nav-link rounded"{% endif %} href="{% url 'main_app:documents'%}">Documents</a>
              </li>
              <li class="nav-item">
                <a {% if request.resolver_match.url_name == 'studentSearch' %}class="nav-link active rounded"{% else %}class="nav-link rounded"{% endif %} href="{% url 'main_app:studentSearch'%}">Student Search</a>
              </li>
              <li class="nav-item">
                <a class="nav-link rounded" style="margin-left: 20px; margin-right:40px; background-color: transparent; color: white" href="{% url 'main_app:logout' %}"> Log Out </a>
              </li>
            </ul>  
        </div>
      </nav>
        {% block content %}
        {% endblock %}
        <footer class="bg-light text-center text-lg-start">
            <div class="text-center p-3" style="background-color: rgba(35, 45, 75, 0.85)">
              Copyright © 2021 Group A-08
            </div>
          </footer>
    </body>
</html>